@startuml
       actor 图书管理员
       图书管理员->借书者:验证借书者
       图书管理员->借书者:取借书者限额
       loop
       图书管理员->资源项:获取资源项
       资源项->馆藏资源:查找资源类别和信息
       图书管理员->借书记录:创建借书记录
       图书管理员->资源项:借出资源
       资源项->馆藏资源:减少可借数量
       图书管理员->借书者:减少可用限额
       end
       图书管理员-->借书记录:打印借书清单
       @enduml