@startuml
actor 借书者用户
借书者用户->借书者:查询帐户信息
借书者-->借书者用户:返回帐户信息
借书者->预订记录:查找预订记录
预订记录-->借书者用户:返回预订信息
借书者->借书记录:查找借书记录
借书记录-->借书者用户:返回借书信息
alt
借书记录->逾期记录:查找逾期记录
逾期记录-->借书者用户:返回逾期信息
逾期记录->罚款记录:查找罚款记录
罚款记录-->借书者用户:返回罚款信息
end
@enduml