@startuml
actor 系统管理员
actor 图书管理员
actor 借书者
系统管理员->资源项:获取资源项
图书管理员->资源项:获取资源项
借书者->资源项:获取资源项
资源项->馆藏资源:查找资源类别和信息
馆藏资源->图书书目:查找图书
图书书目-->系统管理员:返回图书
图书书目-->图书管理员:返回图书
图书书目-->借书者:返回图书
@enduml