@startuml
actor 图书管理员
actor 借书者用户
图书管理员->借书者用户:读取借书者信息
借书者用户->资源项:读取资源信息
资源项->借书记录:取借书记录
资源项->馆藏资源:取资源的类别和信息
借书者用户->资源项:归还资源
资源项->馆藏资源:增加可借数量
图书管理员->借书记录:登记还书日期
opt 逾期
图书管理员->逾期记录:登记逾期记录
借书者-->图书管理员:交付罚金
end
@enduml